/*

 PLAYER.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 16
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char player[] =
{
  0x7E,0x7E,0x42,0x42,0x4A,0x4A,0x42,0x42,
  0x46,0x46,0x7E,0x7E,0x18,0x18,0x19,0x19,
  0x7E,0x7E,0x98,0x98,0x18,0x18,0x3C,0x3C,
  0x24,0x24,0x24,0x24,0x66,0x66,0x66,0x66
};

/* End of PLAYER.C */
